### ISSUE TITLE
DHCP attributes overriding

### ISSUE THREAD

**Issue by zedtux** [sous-chefs/netplan#2]
## :person_frowning: Problem Statement

I had the case where a VPS provider has an incorrect value in its DHCP server which is sending "example.org" as the `domainname` field.

The end result is that my `/etc/resolv.conf` file has this `example.org` in the `search` field.

## :grey_question: Possible Solution

To solve this issue, I had to update the `/etc/netplan/config.yaml` file in order to ignore that value by setting the `use-domains` boolean value to `false` from the `dhcp4-overrides` DHCP override section.

The end file looks like this:

```yaml
network:
  version: 2
  ethernets:
    enp3s0:
      dhcp4: true
      dhcp4-overrides:
        use-domains: false
```
